### ISSUE TITLE
train训练出错，想问一下会什么会出现这个问题呢？

### ISSUE THREAD

**Issue by nnnnnnml** [Linzy0227/SRMNet#3]
2024-06-21 20:26:16,188 Subject 97/100, 1/1BraTS20_Training_353, whole: 0.8999, core: 0.8377, enhancing: 0.6040, enhancing_postpro: 0.6040
h: 0, w: 0, z: -1
weight1 slice shape: torch.Size([1, 1, 128, 128, 1])
one_tensor shape: torch.Size([1, 1, 128, 128, 128])
Traceback (most recent call last):
  File "/home/dell/文档/SRMNet-main/train.py", line 248, in <module>
    main()
  File "/home/dell/文档/SRMNet-main/train.py", line 237, in main
    dice_score = test_softmax(
  File "/home/dell/文档/SRMNet-main/predict.py", line 129, in test_softmax
    raise ValueError(
ValueError: Shape mismatch: weight1 slice shape torch.Size([1, 1, 128, 128, 1]) vs one_tensor shape torch.Size([1, 1, 128, 128, 128])

**Comment by Linzy0227** [comment]
如果是train结束的时候出现这个是正常的，你直接用测试代码测试就可以了，因为train的时候少传了一个路径。
